multitenant env support
apigee/apigee-remote-service-envoy pull request #140
Opened 2021-01-27 19:49 UTC by theganyo

accepts `"*"` as `tenant.env_name` to put it multitenant mode
requires change: https://github.com/apigee/apigee-remote-service-cli/issues/149

For multitenant, Envoy configuration requires the addition of a segment like this to Envoy's `virtual_host` or `route` to specify an environment for ext_authz:
```
                typed_per_filter_config:
                  envoy.filters.http.ext_authz:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
                    check_settings:
                      context_extensions:
                        apigee_environment: test
```

2021-01-27 21:12 UTC, rockspore commented
So it seems possible to enable ext_authz only for specific routes?

2021-01-27 23:47 UTC, theganyo commented
> So it seems possible to enable ext_authz only for specific routes?

Yes. I didn't try that, but it seems like it would be trivial to configure Envoy for that.

2021-01-27 23:49 UTC, rockspore requested changes

2021-01-27 23:49 UTC, rockspore commented on server/authorization.go
> +			return nil, err
What would Envoy do upon receiving a nil response? Would it make sense to send a denial?

2021-01-27 23:49 UTC, rockspore commented on server/authorization_test.go
> +	if resp, err = server.Check(context.Background(), req); err == nil {
This `resp` is unused and should be replaced with `_`.

2021-01-28 17:33 UTC, rockspore commented on server/header_context_test.go
>  	api, ac := h.decodeMetadataHeaders(header)
nit: this `api` assignment is not ineffectual and should be `_`. golangci actually spotted this but had it filtered out.

2021-01-28 17:45 UTC, rockspore approved these changes

2021-01-28 18:13 UTC, merged